import streamlit as st
import tensorflow as tf
from PIL import Image
import numpy as np
import os
import requests
from io import BytesIO


# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Parkinson's Disease Detection",
    page_icon="🧠",
    layout="wide"
)

# --- NAVIGATION SIDEBAR ---
st.sidebar.title("📌 Navigation")
page = st.sidebar.radio("Go to", ["Home", "Prediction", "About"])

# --- CONSTANTS & MODEL LOADING ---
MODEL_PATH = 'parkinson_model.h5'

@st.cache_resource
def load_model():
    """Loads the pre-trained Keras model."""
    if os.path.exists(MODEL_PATH):
        try:
            model = tf.keras.models.load_model(MODEL_PATH)
            return model
        except Exception as e:
            st.error(f"Error loading local model file: {e}")
            return None
    return None

def preprocess_image(image: Image.Image):
    """Preprocesses the PIL Image for CNN model prediction."""
    img = image.convert('RGB')
    img = img.resize((224, 224))
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    return img_array

def make_prediction(model, img_array):
    """Generates prediction and confidence score."""
    if model is None:
        return "Model file missing or failed to load. Please place 'parkinson_model.h5' in the root directory.", 0.0, False
    
    pred = model.predict(img_array)[0][0]
    # Thresholding based on standard sigmoid output (e.g. YES/Affected vs NO/Not affected)
    if pred >= 0.5:
        result = "Parkinson's Disease Detected"
        confidence = float(pred)
    else:
        result = "Normal / Not Affected"
        confidence = float(1 - pred)
    return result, confidence, True

# --- GLOBAL DISCLAIMER ---
def render_disclaimer():
    st.markdown("---")
    st.markdown(
        """
        > **⚠️ Clinical Disclaimer & Notice:**  
        > *This application uses a Deep Learning Convolutional Neural Network (CNN) pipeline designed solely for research and educational purposes. The analysis report generated by this tool does not constitute a formal clinical diagnosis or professional medical advice. Always consult with a qualified healthcare professional for medical evaluations and treatment decisions.*  
        >  
        > **Developer:** Sristi Sarkar | **Accuracy:** 97.0% | **Recall:** 98.84%
        """
    )

# --- 1. HOME PAGE ---
if page == "Home":
    st.title("🧠 Parkinson’s Disease Detection via Deep Learning")
    st.markdown("An automated, non-invasive diagnostic pipeline built to evaluate visual biomarkers using custom Sequential Convolutional Neural Networks (CNN).")
    
    st.subheader("📌 Core Engineering Highlights")
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Test Accuracy", "97.0%")
    with col2:
        st.metric("Recall (Sensitivity)", "98.84%")
    with col3:
        st.metric("Runtime Engine", "TensorFlow 2.19.0")

    st.markdown("---")
    st.subheader("🏗️ Pipeline & Pipeline Execution Architecture")
    st.markdown(
        """
        * **Dataset Preparation:** Input vectors scaled to $224 \\times 224 \\times 3$, normalized ($1/255$), with data augmentations applied (rotation, shear, zoom, horizontal flip).
        * **Sequential CNN Architecture:** Three cascaded 2D Convolution and MaxPooling layers leading to a high-density decision head:
            * `Conv2D` (32 filters, 3x3) $\\rightarrow$ `MaxPooling2D`
            * `Conv2D` (64 filters, 3x3) $\\rightarrow$ `MaxPooling2D`
            * `Conv2D` (128 filters, 3x3) $\\rightarrow$ `MaxPooling2D`
            * `Flatten` $\\rightarrow$ `Dense` (128, ReLU) $\\rightarrow$ `Dropout` (0.5) $\\rightarrow$ `Dense` (1, Sigmoid)
        * **Model Performance:** High recall rates ensure minimal dangerous False Negatives during biomarker scanning.
        """
    )
    
    st.subheader("📊 Performance Matrix")
    st.code(
        """
              precision    recall  f1-score   support

          NO       0.98      0.93      0.95        43
         YES       0.97      0.99      0.98        86

    accuracy                           0.97       129
   macro avg       0.97      0.96      0.96       129
weighted avg       0.97      0.97      0.97       129
        """,
        language="text"
    )

    render_disclaimer()

# --- 2. PREDICTION PAGE ---
elif page == "Prediction":
    st.title("🔍 Inference & Diagnostic Prediction")
    st.write("Analyze sample imagery using the trained Deep Learning diagnostic pipeline.")

    model = load_model()
    if model is None:
        st.warning("⚠️ Local trained model file (`parkinson_model.h5`) not detected. Displaying prediction interface in demonstration mode.")

    option = st.radio("Select Input Method:", ["Upload Image", "Analyze Existing GitHub Sample Images"])

    image_to_analyze = None

    if option == "Upload Image":
        uploaded_file = st.file_uploader("Choose an image (JPG, JPEG, PNG)...", type=["jpg", "jpeg", "png"])
        if uploaded_file is not None:
            image_to_analyze = Image.open(uploaded_file)
            st.image(image_to_analyze, caption="Uploaded Image", use_container_width=True)

    else:
        sample_urls = {
            "Not Affected Sample 1": "https://raw.githubusercontent.com/SristiSarkarMCKV/Parkinson-s-Disease-Detection-using-Various-Deep-Learning-Models/main/Sample/Not%20affected/IMG_20260806_183555.jpg",
            "Affected Sample 1": "https://raw.githubusercontent.com/SristiSarkarMCKV/Parkinson-s-Disease-Detection-using-Various-Deep-Learning-Models/main/Sample/Affected/IMG_20260806_183533.jpg"
        }
        
        selected_sample = st.selectbox("Select Sample Image from Repository Path:", list(sample_urls.keys()))
        sample_url = sample_urls[selected_sample]

        if st.button("Load Selected Sample"):
            with st.spinner("Fetching image from repository..."):
                try:
                    response = requests.get(sample_url)
                    image_to_analyze = Image.open(BytesIO(response.content))
                    st.image(image_to_analyze, caption=f"Loaded: {selected_sample}", use_container_width=True)
                except Exception as e:
                    st.error(f"Failed to retrieve sample image: {e}")

    if image_to_analyze is not None:
        if st.button("⚡ Run Diagnostic Analysis"):
            with st.spinner("Processing image through Deep Learning CNN Pipeline..."):
                img_array = preprocess_image(image_to_analyze)
                result, confidence, success = make_prediction(model, img_array)

                if success:
                    st.markdown("### 📋 Diagnostic Outcome")
                    if "Detected" in result:
                        st.error(f"**Prediction:** {result}")
                    else:
                        st.success(f"**Prediction:** {result}")
                    st.info(f"**Confidence Score:** {confidence * 100:.2f}%")

    render_disclaimer()

# --- 3. ABOUT PAGE ---
elif page == "About":
    st.title("ℹ️ About & Technical Details")

    st.subheader("🤖 Model Description")
    st.markdown(
        """
        * **Architecture:** Sequential Convolutional Neural Network (CNN)
        * **Input Layer:** $(224, 224, 3)$ shape
        * **Total Parameters:** 11,169,089 (42.61 MB)
        * **Optimizer:** Adam
        * **Loss Function:** Binary Cross-Entropy Loss
        * **Epochs Trained:** 10
        * **Dataset Division:** 
            * Train Set: 413 images
            * Validation Set: 103 images
            * Test Set: 129 images
        """
    )

    st.subheader("👤 Developer Details")
    st.markdown(
        """
        * **Name:** Sristi Sarkar
        * **Contact Information:**
            * 📧 **Email:** [emailsristisarkar@gmail.com](mailto:emailsristisarkar@gmail.com)
            * 📞 **Phone:** +91 8240580651
        * **Repository:** [Parkinson's Disease Detection using Deep Learning Models](https://github.com/SristiSarkarMCKV/Parkinson-s-Disease-Detection-using-Various-Deep-Learning-Models)
        """
    )

    render_disclaimer()
